apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{.Name}}
      annotations:
        interlink.eu/wstunnel-path-prefix: {{.RandomPassword}}
    spec:
      containers:
      # ===== WSTunnel Container =====
      - name: wstunnel
        image: ghcr.io/erebe/wstunnel:latest
        imagePullPolicy: IfNotPresent
        command: ["bash","-c"]
        args:
          - >
            ./wstunnel server
            --log-lvl DEBUG
            --dns-resolver-prefer-ipv4
            --restrict-http-upgrade-path-prefix {{.RandomPassword}}
            ws://0.0.0.0:28080
        #--restrict-to 127.0.0.1:51820
        ports:
        - containerPort: 28080
          name: ws
          protocol: TCP
        - containerPort: 51820
          name: vpn
          protocol: UDP
        {{- range .ExposedPorts}}
        - containerPort: {{.Port}}
          name: {{if .Name}}{{.Name}}{{else}}port-{{.Port}}{{end}}
          protocol: {{.Protocol}}
        {{- end}}
        resources:
          requests:
            cpu: 100m
            memory: 90Mi
        readinessProbe:
          tcpSocket:
            port: 28080
          initialDelaySeconds: 2
          periodSeconds: 2
          failureThreshold: 10
        livenessProbe:
          tcpSocket:
            port: 28080
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: {{.Name}}
  ports:
    - port: 28080
      targetPort: 28080
      name: ws
      protocol: TCP
    {{- range .ExposedPorts}}
    - port: {{.Port}}
      targetPort: {{.Port}}
      name: {{.Name}}
      protocol: {{.Protocol}}
    {{- end}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  annotations:
    # Traefik-specific annotations for WebSocket
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{.Name}}-{{.Namespace}}.{{.WildcardDNS}}
  rules:
  - host: {{.Name}}-{{.Namespace}}.{{.WildcardDNS}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Name}}
            port:
              number: 28080