apiVersion: v1
kind: ConfigMap
metadata:
  name: wstunnel-template
  namespace: interlink
data:
  custom-wstunnel.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{.Name}}
      namespace: {{.Namespace}}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/component: {{.Name}}
      template:
        metadata:
          labels:
            app.kubernetes.io/component: {{.Name}}
        spec:
          containers:
          - name: wireguard
            image: ghcr.io/dciangot/dciangot/wg:v0.2
            command: ["bash", "-c"]
            args:
            - ./wstunnel server --log-lvl DEBUG --dns-resolver-prefer-ipv4 --restrict-http-upgrade-path-prefix {{.RandomPassword}} ws://0.0.0.0:8080
            ports:
            - containerPort: 8080
              name: webhook
              protocol: TCP
            {{- range .ExposedPorts}}
            - containerPort: {{.Port}}
              name: {{.Name}}
              protocol: {{.Protocol}}
            {{- end}}
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: {{.Name}}
      namespace: {{.Namespace}}
    spec:
      type: ClusterIP
      selector:
        app.kubernetes.io/component: {{.Name}}
      ports:
        - port: 8080
          targetPort: 8080
          name: ws
        {{- range .ExposedPorts}}
        - port: {{.Port}}
          targetPort: {{.TargetPort}}
          name: {{.Name}}
          protocol: {{.Protocol}}
        {{- end}}
    ---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: {{.Name}}
      namespace: {{.Namespace}}
      annotations:
        # Traefik annotations instead of nginx
        kubernetes.io/ingress.class: "traefik"
        traefik.ingress.kubernetes.io/router.entrypoints: "web"
    spec:
      rules:
      - host: ws-{{.Name}}.{{.WildcardDNS}}
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Name}}
                port:
                  number: 8080